### PR TITLE
Fixed #3 : Migrated to Requests

### LINKED ISSUE #3: Migrate to requests
- Using browser to view a website is a bad idea. (heavy framework)
- requests with bs4 gels great.
- Requests gives more flexibility to the developer

### PR DESCRIPTION
**Pull request by 0x48piraj**
> Using browser framework to view a website is a bad idea. (heavy framework for just requesting a website)

## Changes Proposed : 

- Migrated the code to use `requests` module.

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Ping @SubhrajitPrusty

**Comment by 0x48piraj** [comment]
Ping @SubhrajitPrusty :1st_place_medal:

**Review by SubhrajitPrusty — CHANGES_REQUESTED** [review]
This gets a lot of profile pics. Exclude that.
All the downloads should be put in their separate tag folder.

**Comment by 0x48piraj** [comment]
Why not we make two versions, one with requests, another with broswer frameworks. Will you make a backup branch then accept this PR so that I can work on this?

**Comment by 0x48piraj** [comment]
Second PR will include both the things you asked :)

**Comment by 0x48piraj** [comment]
Deleting the PR as the maintainer is good with wget.

**Pull request closed without merging**
